name: Actualizar datos especies

on:
  schedule:
    - cron: '0 12 * * *'   # Todos los días a las 12:00 UTC
  workflow_dispatch:       # También puedes lanzarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias (si usas alguna)
        run: pip install -r requirements.txt || echo "No hay requirements"

      - name: Ejecutar script
        run: python scripts/animales_lista.py

      - name: Hacer commit si hay cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Actualizar datos automáticamente" || echo "Sin cambios"
          git push

